/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedDistribuirRouteImport } from './routes/_authenticated/distribuir'
import { Route as AuthenticatedPainelRouteImport } from './routes/_authenticated/painel'
import { Route as AuthenticatedUsuariosRouteImport } from './routes/_authenticated/usuarios'
import { Route as AuthenticatedAtividadesIndexRouteImport } from './routes/_authenticated/atividades/index'
import { Route as AuthenticatedAtividadesActivityIdRouteImport } from './routes/_authenticated/atividades/$activityId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDistribuirRoute = AuthenticatedDistribuirRouteImport.update({
  id: '/distribuir',
  path: '/distribuir',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPainelRoute = AuthenticatedPainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedUsuariosRoute = AuthenticatedUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAtividadesIndexRoute =
  AuthenticatedAtividadesIndexRouteImport.update({
    id: '/atividades/',
    path: '/atividades/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAtividadesActivityIdRoute =
  AuthenticatedAtividadesActivityIdRouteImport.update({
    id: '/atividades/$activityId',
    path: '/atividades/$activityId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/distribuir': typeof AuthenticatedDistribuirRoute
  '/painel': typeof AuthenticatedPainelRoute
  '/usuarios': typeof AuthenticatedUsuariosRoute
  '/atividades/$activityId': typeof AuthenticatedAtividadesActivityIdRoute
  '/atividades/': typeof AuthenticatedAtividadesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/distribuir': typeof AuthenticatedDistribuirRoute
  '/painel': typeof AuthenticatedPainelRoute
  '/usuarios': typeof AuthenticatedUsuariosRoute
  '/atividades/$activityId': typeof AuthenticatedAtividadesActivityIdRoute
  '/atividades': typeof AuthenticatedAtividadesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_authenticated/distribuir': typeof AuthenticatedDistribuirRoute
  '/_authenticated/painel': typeof AuthenticatedPainelRoute
  '/_authenticated/usuarios': typeof AuthenticatedUsuariosRoute
  '/_authenticated/atividades/$activityId': typeof AuthenticatedAtividadesActivityIdRoute
  '/_authenticated/atividades/': typeof AuthenticatedAtividadesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/distribuir'
    | '/painel'
    | '/usuarios'
    | '/atividades/$activityId'
    | '/atividades/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/distribuir'
    | '/painel'
    | '/usuarios'
    | '/atividades/$activityId'
    | '/atividades'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_authenticated/distribuir'
    | '/_authenticated/painel'
    | '/_authenticated/usuarios'
    | '/_authenticated/atividades/$activityId'
    | '/_authenticated/atividades/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/distribuir': {
      id: '/_authenticated/distribuir'
      path: '/distribuir'
      fullPath: '/distribuir'
      preLoaderRoute: typeof AuthenticatedDistribuirRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/painel': {
      id: '/_authenticated/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof AuthenticatedPainelRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/usuarios': {
      id: '/_authenticated/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof AuthenticatedUsuariosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/atividades/': {
      id: '/_authenticated/atividades/'
      path: '/atividades'
      fullPath: '/atividades/'
      preLoaderRoute: typeof AuthenticatedAtividadesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/atividades/$activityId': {
      id: '/_authenticated/atividades/$activityId'
      path: '/atividades/$activityId'
      fullPath: '/atividades/$activityId'
      preLoaderRoute: typeof AuthenticatedAtividadesActivityIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDistribuirRoute: typeof AuthenticatedDistribuirRoute
  AuthenticatedPainelRoute: typeof AuthenticatedPainelRoute
  AuthenticatedUsuariosRoute: typeof AuthenticatedUsuariosRoute
  AuthenticatedAtividadesActivityIdRoute: typeof AuthenticatedAtividadesActivityIdRoute
  AuthenticatedAtividadesIndexRoute: typeof AuthenticatedAtividadesIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDistribuirRoute: AuthenticatedDistribuirRoute,
  AuthenticatedPainelRoute: AuthenticatedPainelRoute,
  AuthenticatedUsuariosRoute: AuthenticatedUsuariosRoute,
  AuthenticatedAtividadesActivityIdRoute:
    AuthenticatedAtividadesActivityIdRoute,
  AuthenticatedAtividadesIndexRoute: AuthenticatedAtividadesIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
